"""Regression tests for committed Netlify frontend deployment targets."""

from __future__ import annotations

from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[1]
NETLIFY_CONFIG = ROOT / "netlify.toml"
FRONTEND_GITIGNORE = ROOT / "frontend/.gitignore"
EXPECTED_API_URL = "https://web-production-7f848.up.railway.app"
EXPECTED_WS_URL = "wss://web-production-7f848.up.railway.app/ws/agent"


def _build_environment(path: Path) -> dict[str, str]:
    with path.open("rb") as handle:
        data = tomllib.load(handle)
    return data["build"]["environment"]


def test_committed_netlify_config_targets_the_current_railway_backend() -> None:
    """The checked-in Netlify config should point at the live Railway backend domain."""
    env = _build_environment(NETLIFY_CONFIG)

    assert env["VITE_API_URL"] == EXPECTED_API_URL
    assert env["VITE_WS_URL"] == EXPECTED_WS_URL


def test_frontend_netlify_artifacts_are_ignored() -> None:
    """Autogenerated frontend .netlify output should stay ignored by Git."""
    ignore_lines = {line.strip() for line in FRONTEND_GITIGNORE.read_text().splitlines()}
    assert ".netlify/" in ignore_lines
