import type { DocsPage, DocsSectionMeta } from './types'

export const DOCS_SECTIONS: DocsSectionMeta[] = [
  {
    id: 'guides',
    title: 'Guides',
    description: 'Core product guidance for setup, auth, live sessions, workflows, and deployment.',
  },
  {
    id: 'tutorials',
    title: 'Tutorials',
    description: 'End-to-end examples for real operator workflows and first-run experiences.',
  },
  {
    id: 'reference',
    title: 'API Reference',
    description: 'HTTP routes, WebSocket actions, event payloads, and environment contract details.',
  },
  {
    id: 'support',
    title: 'Support',
    description: 'FAQ answers, changelog entries, and operational notes for launch readiness.',
  },
]

export const DOCS_PAGES: DocsPage[] = [
  {
    slug: 'quickstart',
    title: 'Quickstart',
    summary: 'Bring Aegis online locally, sign in, connect a model, and run your first session in minutes.',
    section: 'guides',
    audience: 'New operators',
    updatedAt: '2026-03-19',
    featured: true,
    related: ['authentication', 'provider-keys', 'live-sessions', 'first-live-run'],
    blocks: [
      { type: 'paragraph', text: 'Aegis is designed to move quickly from zero to a live UI navigation session. The fastest path is to configure one model provider, sign in, and open the browser session with the signed-in app shell.' },
      { type: 'steps', items: [
        { title: 'Run the backend', body: 'Install Python dependencies, make sure Playwright Chromium is available, and start FastAPI on the configured PORT.' },
        { title: 'Run the frontend', body: 'Start the Vite frontend and open the main app domain. Unsigned users land on the public site first.' },
        { title: 'Create or sign in to an account', body: 'Use password auth, GitHub, Google, or generic SSO depending on the environment configuration.' },
        { title: 'Connect a provider key', body: 'Open Settings and store at least one provider key if you are using BYOK instead of platform fallbacks.' },
        { title: 'Start a live session', body: 'Use the input bar or voice capture to give the first instruction, then watch the chat stream for progress and results.' },
      ] },
      { type: 'callout', tone: 'info', title: 'Docs surface strategy', body: 'This guide lives inside the embedded docs surface of the main product. The content is driven by a single shared docs source so every view stays synchronized.' },
      { type: 'code', language: 'bash', code: 'cp .env.example .env\nuvicorn main:app --reload --port 8000\n\ncd frontend\nnpm install\nnpm run dev' },
      { type: 'linkCards', items: [
        { slug: 'authentication', title: 'Authentication', description: 'Sign-in, sign-up, SSO, and callback flow details.' },
        { slug: 'provider-keys', title: 'Provider keys', description: 'Use your own OpenAI, Anthropic, Gemini, Mistral, or Groq credentials.' },
        { slug: 'deployment', title: 'Deployment', description: 'Prepare Railway or another platform for backend hosting.' },
      ] },
    ],
  },
  {
    slug: 'authentication',
    title: 'Authentication',
    summary: 'How sign-in, sign-up, OAuth, SSO, and session cookies work across the Aegis surfaces.',
    section: 'guides',
    audience: 'Operators and admins',
    updatedAt: '2026-03-19',
    featured: true,
    related: ['quickstart', 'deployment', 'api-auth-reference'],
    blocks: [
      { type: 'paragraph', text: 'The main app domain owns the canonical auth entry point. Unsigned users can move from the landing page into the auth page, complete authentication, and then enter the signed-in operator shell.' },
      { type: 'heading', text: 'Supported auth modes' },
      { type: 'list', items: [
        'Email and password sign-up plus password login',
        'Google OAuth login',
        'GitHub OAuth login',
        'Generic OIDC SSO',
      ] },
      { type: 'heading', text: 'Session behavior' },
      { type: 'paragraph', text: 'Sessions are issued through an HTTP-only aegis_session cookie. Keep the frontend and backend origin strategy in mind when deploying auth-sensitive flows.' },
      { type: 'table', columns: ['Config', 'Purpose'], rows: [
        ['SESSION_SECRET', 'Signs and verifies the session cookie payload.'],
        ['PUBLIC_BASE_URL', 'Builds OAuth callback URLs for backend auth routes.'],
        ['FRONTEND_URL', 'Redirect target after successful OAuth completion.'],
        ['COOKIE_SECURE', 'Enables secure-only cookies in HTTPS environments.'],
      ] },
    ],
  },
  {
    slug: 'provider-keys',
    title: 'Provider keys and BYOK',
    summary: 'Connect your own provider keys, understand defaults, and manage fallbacks.',
    section: 'guides',
    audience: 'Operators and admins',
    updatedAt: '2026-03-19',
    related: ['quickstart', 'api-auth-reference', 'deployment'],
    blocks: [
      { type: 'paragraph', text: 'Aegis supports Bring Your Own Key across multiple providers so billing and quota stay under your control.' },
      { type: 'list', items: [
        'OpenAI',
        'Anthropic',
        'Google Gemini',
        'Mistral',
        'Groq',
      ] },
      { type: 'callout', tone: 'success', title: 'Storage model', body: 'User provider keys are encrypted before persistence. Server-side fallback keys can also be configured through environment variables.' },
      { type: 'code', language: 'env', code: 'OPENAI_API_KEY=\nANTHROPIC_API_KEY=\nGEMINI_API_KEY=\nMISTRAL_API_KEY=\nGROQ_API_KEY=' },
      { type: 'paragraph', text: 'If a user key is present for the selected provider, Aegis can prioritize that key. If no user key is available, platform fallbacks can be used when configured.' },
    ],
  },
  {
    slug: 'live-sessions',
    title: 'Live sessions',
    summary: 'Understand the operator shell, chat-driven task loop, streaming updates, and task lifecycle.',
    section: 'guides',
    audience: 'Operators',
    updatedAt: '2026-04-23',
    featured: true,
    related: ['voice-and-transcripts', 'workflow-templates', 'websocket-reference'],
    blocks: [
      { type: 'paragraph', text: 'A live session combines the chat thread, streaming reasoning, workflow view, steering controls, and optional voice input into one real-time operator surface. Browser work happens through agent tools and does not require a visible browser frame.' },
      { type: 'steps', items: [
        { title: 'Start a task', body: 'When the operator sends the first instruction, the session config is pushed and the run begins.' },
        { title: 'Watch live state', body: 'Assistant tokens, tool calls, and workflow steps stream into the chat surface in parallel.' },
        { title: 'Steer or interrupt', body: 'The operator can send a steer note, interrupt the current run, or queue follow-up work.' },
        { title: 'Capture workflow output', body: 'Workflow templates can be saved from the chat stream for later reuse.' },
      ] },
      { type: 'callout', tone: 'info', title: 'Signed-in shell separation', body: 'The signed-in app shell should remain distinct from the public landing, auth, and embedded docs surfaces.' },
    ],
  },
  {
    slug: 'voice-and-transcripts',
    title: 'Voice and transcripts',
    summary: 'Mic capture, Live API session handling, transcript display, and operator feedback loops.',
    section: 'guides',
    audience: 'Operators',
    updatedAt: '2026-03-19',
    related: ['live-sessions', 'websocket-reference'],
    blocks: [
      { type: 'paragraph', text: 'Voice support lets operators push spoken instructions into a Live API session. Transcript events can be surfaced in the UI and used to steer or launch tasks.' },
      { type: 'list', items: [
        'Mic capture starts from the frontend input area.',
        'Audio chunks are forwarded over the session WebSocket.',
        'Transcripts are streamed back into the UI and can trigger task execution when idle.',
      ] },
      { type: 'code', language: 'json', code: '{\n  "action": "audio_chunk",\n  "audio": "<base64-pcm-payload>"\n}' },
    ],
  },
  {
    slug: 'workflow-templates',
    title: 'Workflow templates',
    summary: 'Save recurring instructions, edit them, and run them back through the signed-in shell.',
    section: 'guides',
    audience: 'Operators and team leads',
    updatedAt: '2026-03-19',
    related: ['live-sessions', 'integrations', 'first-live-run'],
    blocks: [
      { type: 'paragraph', text: 'Workflow templates let operators turn successful runs into reusable entry points. They live inside settings and can be launched back into the main app shell.' },
      { type: 'list', items: [
        'Save workflow from an action log',
        'Edit workflow instructions in settings',
        'Run workflows directly from the templates list',
      ] },
    ],
  },
  {
    slug: 'integrations',
    title: 'Integrations',
    summary: 'Telegram, Slack, Discord, and related connector flows in the current product surface.',
    section: 'guides',
    audience: 'Admins and operators',
    updatedAt: '2026-03-19',
    related: ['deployment', 'workflow-templates', 'api-auth-reference'],
    blocks: [
      { type: 'paragraph', text: 'Aegis exposes integration setup and testing flows for messaging platforms. These connectors can be used for notifications, summaries, and delegated outputs.' },
      { type: 'table', columns: ['Integration', 'Current focus'], rows: [
        ['Telegram', 'Webhook or polling setup plus message delivery routes'],
        ['Slack', 'Workspace connector plus send_message and test flows'],
        ['Discord', 'Guild connector plus send_message and test flows'],
      ] },
      { type: 'callout', tone: 'warning', title: 'Production note', body: 'Real connector behavior depends on valid platform credentials and network reachability in the deployed environment.' },
    ],
  },
  {
    slug: 'deployment',
    title: 'Deployment',
    summary: 'Backend hosting, frontend hosting, environment variables, and cross-origin deployment concerns.',
    section: 'guides',
    audience: 'Operators and platform owners',
    updatedAt: '2026-03-19',
    featured: true,
    related: ['authentication', 'api-auth-reference', 'quickstart'],
    blocks: [
      { type: 'paragraph', text: 'Aegis can be deployed with the backend and main frontend together, or with the backend on one platform and the public/docs frontends elsewhere. Auth and cookie behavior should be planned explicitly.' },
      { type: 'heading', text: 'Core deployment inputs' },
      { type: 'table', columns: ['Variable', 'Why it matters'], rows: [
        ['DATABASE_URL', 'Connects the backend to Postgres or another supported database URL.'],
        ['PUBLIC_BASE_URL', 'Used to build OAuth callback URLs.'],
        ['FRONTEND_URL', 'Used for OAuth redirect completion.'],
        ['PORT', 'Runtime binding required by platforms such as Railway or Cloud Run.'],
      ] },
      { type: 'code', language: 'env', code: 'DATABASE_URL=postgresql://...\nPUBLIC_BASE_URL=https://api.example.com\nFRONTEND_URL=https://app.example.com\nCOOKIE_SECURE=true' },
      { type: 'callout', tone: 'info', title: 'Railway note', body: 'The current codebase already includes Railway deployment metadata and a root Dockerfile that respects PORT and /health.' },
    ],
  },
  {
    slug: 'first-live-run',
    title: 'Tutorial: first live run',
    summary: 'A walk-through for signing in, configuring a provider, and running the first operator task.',
    section: 'tutorials',
    audience: 'New operators',
    updatedAt: '2026-03-19',
    featured: true,
    related: ['quickstart', 'live-sessions', 'voice-and-transcripts'],
    blocks: [
      { type: 'steps', items: [
        { title: 'Open the public site', body: 'Read the landing page overview and jump into auth.' },
        { title: 'Sign in or create an account', body: 'Use email/password or a configured SSO provider.' },
        { title: 'Open Settings', body: 'Confirm the provider and model selection, and add BYOK credentials if needed.' },
        { title: 'Send a first instruction', body: 'Use the input bar or voice mode to start a task.' },
        { title: 'Save a useful run as a workflow', body: 'Turn a successful pattern into a reusable template.' },
      ] },
    ],
  },
  {
    slug: 'api-auth-reference',
    title: 'API reference: auth and HTTP routes',
    summary: 'HTTP endpoints for auth, keys, providers, and integration registration.',
    section: 'reference',
    audience: 'Developers',
    updatedAt: '2026-03-19',
    featured: true,
    related: ['websocket-reference', 'authentication', 'deployment'],
    blocks: [
      { type: 'table', columns: ['Method', 'Route', 'Purpose'], rows: [
        ['GET', '/health', 'Health check used by runtime platforms.'],
        ['GET', '/api/providers', 'List supported model providers and models.'],
        ['POST', '/api/auth/password/signup', 'Create a password-based account.'],
        ['POST', '/api/auth/password/login', 'Sign in to an existing password-based account.'],
        ['GET', '/api/auth/me', 'Return the current authenticated user.'],
        ['POST', '/api/auth/logout', 'Clear the auth session cookie.'],
        ['GET', '/api/auth/google/login', 'Start Google OAuth.'],
        ['GET', '/api/auth/github/login', 'Start GitHub OAuth.'],
      ] },
      { type: 'callout', tone: 'info', title: 'Callback URLs', body: 'OAuth callbacks are built from PUBLIC_BASE_URL and resolve under /api/auth/<provider>/callback.' },
    ],
  },
  {
    slug: 'websocket-reference',
    title: 'API reference: WebSocket session contract',
    summary: 'The action and event contract for /ws/navigate.',
    section: 'reference',
    audience: 'Developers',
    updatedAt: '2026-03-19',
    related: ['live-sessions', 'voice-and-transcripts', 'api-auth-reference'],
    blocks: [
      { type: 'table', columns: ['Client action', 'Purpose'], rows: [
        ['navigate', 'Start a new task when idle.'],
        ['steer', 'Append a steering note during a run.'],
        ['interrupt', 'Cancel current execution and start a new instruction.'],
        ['queue', 'Queue a follow-up instruction.'],
        ['dequeue', 'Remove a queued instruction by index.'],
        ['config', 'Push current session settings before task execution.'],
        ['audio_chunk', 'Forward encoded audio to the live audio session.'],
        ['stop', 'Terminate the session.'],
      ] },
      { type: 'table', columns: ['Server event', 'Meaning'], rows: [
        ['step', 'Execution update — streams assistant tokens, tool calls, reasoning, and handoffs into the chat surface.'],
        ['workflow_step', 'Structured workflow view update.'],
        ['transcript', 'Transcript text from voice input.'],
        ['result', 'Task completion payload.'],
        ['error', 'Recoverable session or protocol error.'],
      ] },
      { type: 'code', language: 'json', code: '{\n  "action": "navigate",\n  "instruction": "Go to Google and search for the latest AI news"\n}' },
    ],
  },
  {
    slug: 'faq',
    title: 'FAQ',
    summary: 'Answers to common product, deployment, and operator questions.',
    section: 'support',
    audience: 'All users',
    updatedAt: '2026-03-19',
    featured: true,
    related: ['quickstart', 'deployment', 'voice-and-transcripts'],
    blocks: [
      { type: 'faq', items: [
        { question: 'Does Aegis require DOM selectors?', answer: 'No. The core product direction is vision-first. The agent reasons from screenshots and UI state instead of depending on brittle selectors.' },
        { question: 'Can I use my own model provider keys?', answer: 'Yes. BYOK is a first-class product concept and the UI already supports managing provider credentials.' },
        { question: 'Can docs be browsed without signing in?', answer: 'Yes. Embedded docs are public inside the main app domain.' },
        { question: 'Does Aegis support voice?', answer: 'Yes. The signed-in shell can stream audio chunks, receive transcripts, and display transcript feedback in the UI.' },
      ] },
    ],
  },
  {
    slug: 'changelog',
    title: 'Changelog',
    summary: 'Launch-facing product and platform updates.',
    section: 'support',
    audience: 'All users',
    updatedAt: '2026-04-02',
    related: ['faq', 'quickstart', 'deployment'],
    blocks: [
      { type: 'timeline', items: [
        { date: '2026-04-23', title: 'Chat-only operator surface', description: 'The split-surface browser frame and manual handoff UI were retired. Operators now steer Aegis through a single chat thread; browser work runs as agent tools via the MCP host.' },
        { date: '2026-04-23', title: 'Connectors as first-class agent tools', description: 'Notion, GitHub, Google, Linear, and Slack connectors are registered alongside native and MCP tools with automatic namespace deduplication.' },
        { date: '2026-03-19', title: 'Public site and embedded docs architecture defined', description: 'Aegis moved toward a story-led landing page and shared docs content embedded inside the main app.' },
        { date: '2026-03-18', title: 'Real sign-up and password auth flow', description: 'Auth moved from temporary sign-in handling to a real sign-up and password-verification flow backed by stored hashes.' },
        { date: '2026-03-18', title: 'Frontend build cleanup', description: 'Key TypeScript build blockers in the signed-in shell were resolved and the auth flow was retested.' },
      ] },
    ],
  },
]
